# Generated by Django 5.0.6 on 2024-07-30 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('author', models.CharField(max_length=100, verbose_name='Автор')),
                ('publication_year', models.IntegerField(verbose_name='Год публикации')),
                ('description', models.TextField(verbose_name='Описание')),
                ('cover_image', models.URLField(verbose_name='Фотография')),
                ('reading',  models.TextField(max_length=100, default=None, verbose_name="читать")),
            ],
        ),
    ]
