# Generated by Django 5.0.7 on 2024-08-10 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='reading',
            field=models.TextField(null=True, max_length=100, verbose_name='читать'),
        ),
    ]
