# Generated by Django 5.0.7 on 2024-08-14 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_book_reading'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='reading',
            field=models.TextField(max_length=100, null=True, verbose_name='читать'),
        ),
    ]
